#' @importFrom ggplot2 %+replace%
NULL

#' Simple default themes for plots
#'
#' @description Simple default themes for `ggplot2` plots generated by the
#' `pdallele` plotting functions. Largely based on [ggplot2::theme_gray()] with
#' [ggplot2::element_text()] replaced by [ggtext::element_markdown()] and other
#' elements modified or hidden as needed for donut plots and heat maps.
#'
#' @inheritParams ggplot2::theme_gray
#' @export
theme_simple <- function(base_size = 11, base_family = "",
                     base_line_size = base_size / 22,
                     base_rect_size = base_size / 22) {
  # Starts with theme_void and then modify some parts
  ggplot2::theme_minimal(
    base_size = base_size,
    base_family = base_family,
    base_line_size = base_line_size,
    base_rect_size = base_rect_size
  ) %+replace%
    ggplot2::theme(
      # Add ggtext::element_markdown() to in-use text
      legend.text      = ggtext::element_markdown(),
      legend.title     = ggtext::element_markdown(),
      axis.text.x      = ggtext::element_markdown(),
      axis.text.y      = ggtext::element_markdown(),

      # Bold some useful text
      strip.text       = ggtext::element_markdown(face = "bold"),

      complete = TRUE
    )
}

#' Additional theme elements for `pdallele` donut plots
#' @rdname theme_simple
#' @inheritParams theme_simple
#' @export
theme_donut <- function(base_size = 11, base_family = "",
                        base_line_size = base_size / 22,
                        base_rect_size = base_size / 22) {
  # Starts with theme_simple and then modify some parts
  theme_simple(
    base_size = base_size,
    base_family = base_family,
    base_line_size = base_line_size,
    base_rect_size = base_rect_size
  ) %+replace%
    ggplot2::theme(
      panel.background = ggplot2::element_blank(),
      panel.grid = ggplot2::element_blank(),
      axis.title = ggplot2::element_blank(),
      axis.ticks = ggplot2::element_blank(),
      axis.text = ggplot2::element_blank(),
      axis.text.x = ggplot2::element_blank(),
      axis.text.y = ggplot2::element_blank(),

      complete = TRUE
    )
}

#' Additional theme elements for `pdallele` heatmaps
#' @rdname theme_simple
#' @inheritParams theme_simple
#' @export
theme_heatmap <- function(base_size = 11, base_family = "",
                        base_line_size = base_size / 22,
                        base_rect_size = base_size / 22) {
  # Starts with theme_simple and then modify some parts
  theme_simple(
    base_size = base_size,
    base_family = base_family,
    base_line_size = base_line_size,
    base_rect_size = base_rect_size
  ) %+replace%
    ggplot2::theme(
      axis.title = ggplot2::element_blank(),
      axis.text.x = ggtext::element_markdown(angle = 90, vjust = 0.5),
      axis.text.y = ggtext::element_markdown(),
      axis.ticks = ggplot2::element_blank(),

      panel.background = ggplot2::element_blank(),
      panel.spacing = ggplot2::unit(0.5, "in"),
      strip.background = ggplot2::element_blank(),
      strip.text = ggplot2::element_blank(),

      complete = TRUE
    )
}
